---
abstract: 'Draw building flowcharts from Makefiles using GraphViz'
author:
  - "Yichun \"agentzh\" Zhang (章亦春) C<< <agentzh@gmail.com> >>"
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Compare: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Makefile-GraphViz
no_index:
  directory:
    - inc
    - samples
    - t
requires:
  GraphViz: 2.16
  Makefile::Parser: 0.216
  perl: 5.6.1
resources:
  license: http://opensource.org/licenses/bsd-license.php
  repository: https://github.com/agentzh/makefile-graphviz-pm
version: 0.21
