---
abstract: 'Draw building flowcharts from Makefiles using GraphViz'
author:
  - "Zhang \"agentzh\" Yichun (章亦春) C<< <agentzh@gmail.com> >>"
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Compare: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Makefile-GraphViz
no_index:
  directory:
    - inc
    - samples
    - t
requires:
  GraphViz: 2.02
  Makefile::Parser: 0.210
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/agentzh/makefile-graphviz-pm
version: 0.18
